runtime: php55
api_version: 1
threadsafe: true

handlers:
  - url: /
    static_dir: www/
    http_headers:
      Access-Control-Allow-Origin: '*'
      Access-Control-Allow-Methods: 'GET, OPTIONS'
      Access-Control-Max-Age: '1000'
      Access-Control-Allow-Headers: 'Content-Type, origin, accept, If-Modified-Since, Pragma, Cache-Control'